//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace YoDigital.net.azurewebsites.sgoweb {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SQLSoap", Namespace="http://tempuri.org/")]
    public partial class SQL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Data_SQL_NonQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_SQL_QueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_SQL_NonQueryBinarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Data_SQL_Async_QueryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SQL() {
            this.Url = global::YoDigital.Properties.Settings.Default.YoDigital_net_azurewebsites_sgoweb_SQL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Data_SQL_NonQueryCompletedEventHandler Data_SQL_NonQueryCompleted;
        
        /// <remarks/>
        public event Data_SQL_QueryCompletedEventHandler Data_SQL_QueryCompleted;
        
        /// <remarks/>
        public event Data_SQL_NonQueryBinarioCompletedEventHandler Data_SQL_NonQueryBinarioCompleted;
        
        /// <remarks/>
        public event Data_SQL_Async_QueryCompletedEventHandler Data_SQL_Async_QueryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_SQL_NonQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Data_SQL_NonQuery(string _SQLQuery, string _Catalogo) {
            object[] results = this.Invoke("Data_SQL_NonQuery", new object[] {
                        _SQLQuery,
                        _Catalogo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Data_SQL_NonQueryAsync(string _SQLQuery, string _Catalogo) {
            this.Data_SQL_NonQueryAsync(_SQLQuery, _Catalogo, null);
        }
        
        /// <remarks/>
        public void Data_SQL_NonQueryAsync(string _SQLQuery, string _Catalogo, object userState) {
            if ((this.Data_SQL_NonQueryOperationCompleted == null)) {
                this.Data_SQL_NonQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_SQL_NonQueryOperationCompleted);
            }
            this.InvokeAsync("Data_SQL_NonQuery", new object[] {
                        _SQLQuery,
                        _Catalogo}, this.Data_SQL_NonQueryOperationCompleted, userState);
        }
        
        private void OnData_SQL_NonQueryOperationCompleted(object arg) {
            if ((this.Data_SQL_NonQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_SQL_NonQueryCompleted(this, new Data_SQL_NonQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_SQL_Query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Data_SQL_Query(string _SQLQuery, string _Catalogo) {
            object[] results = this.Invoke("Data_SQL_Query", new object[] {
                        _SQLQuery,
                        _Catalogo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Data_SQL_QueryAsync(string _SQLQuery, string _Catalogo) {
            this.Data_SQL_QueryAsync(_SQLQuery, _Catalogo, null);
        }
        
        /// <remarks/>
        public void Data_SQL_QueryAsync(string _SQLQuery, string _Catalogo, object userState) {
            if ((this.Data_SQL_QueryOperationCompleted == null)) {
                this.Data_SQL_QueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_SQL_QueryOperationCompleted);
            }
            this.InvokeAsync("Data_SQL_Query", new object[] {
                        _SQLQuery,
                        _Catalogo}, this.Data_SQL_QueryOperationCompleted, userState);
        }
        
        private void OnData_SQL_QueryOperationCompleted(object arg) {
            if ((this.Data_SQL_QueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_SQL_QueryCompleted(this, new Data_SQL_QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_SQL_NonQueryBinario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Data_SQL_NonQueryBinario(string _SQLQuery, string _Catalogo, string[] Parametros, byte[][] arrByte) {
            object[] results = this.Invoke("Data_SQL_NonQueryBinario", new object[] {
                        _SQLQuery,
                        _Catalogo,
                        Parametros,
                        arrByte});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Data_SQL_NonQueryBinarioAsync(string _SQLQuery, string _Catalogo, string[] Parametros, byte[][] arrByte) {
            this.Data_SQL_NonQueryBinarioAsync(_SQLQuery, _Catalogo, Parametros, arrByte, null);
        }
        
        /// <remarks/>
        public void Data_SQL_NonQueryBinarioAsync(string _SQLQuery, string _Catalogo, string[] Parametros, byte[][] arrByte, object userState) {
            if ((this.Data_SQL_NonQueryBinarioOperationCompleted == null)) {
                this.Data_SQL_NonQueryBinarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_SQL_NonQueryBinarioOperationCompleted);
            }
            this.InvokeAsync("Data_SQL_NonQueryBinario", new object[] {
                        _SQLQuery,
                        _Catalogo,
                        Parametros,
                        arrByte}, this.Data_SQL_NonQueryBinarioOperationCompleted, userState);
        }
        
        private void OnData_SQL_NonQueryBinarioOperationCompleted(object arg) {
            if ((this.Data_SQL_NonQueryBinarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_SQL_NonQueryBinarioCompleted(this, new Data_SQL_NonQueryBinarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Data_SQL_Async_Query", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Data_SQL_Async_Query(string _SQLQuery, string _Catalogo) {
            object[] results = this.Invoke("Data_SQL_Async_Query", new object[] {
                        _SQLQuery,
                        _Catalogo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Data_SQL_Async_QueryAsync(string _SQLQuery, string _Catalogo) {
            this.Data_SQL_Async_QueryAsync(_SQLQuery, _Catalogo, null);
        }
        
        /// <remarks/>
        public void Data_SQL_Async_QueryAsync(string _SQLQuery, string _Catalogo, object userState) {
            if ((this.Data_SQL_Async_QueryOperationCompleted == null)) {
                this.Data_SQL_Async_QueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnData_SQL_Async_QueryOperationCompleted);
            }
            this.InvokeAsync("Data_SQL_Async_Query", new object[] {
                        _SQLQuery,
                        _Catalogo}, this.Data_SQL_Async_QueryOperationCompleted, userState);
        }
        
        private void OnData_SQL_Async_QueryOperationCompleted(object arg) {
            if ((this.Data_SQL_Async_QueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Data_SQL_Async_QueryCompleted(this, new Data_SQL_Async_QueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Data_SQL_NonQueryCompletedEventHandler(object sender, Data_SQL_NonQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_SQL_NonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_SQL_NonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Data_SQL_QueryCompletedEventHandler(object sender, Data_SQL_QueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_SQL_QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_SQL_QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Data_SQL_NonQueryBinarioCompletedEventHandler(object sender, Data_SQL_NonQueryBinarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_SQL_NonQueryBinarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_SQL_NonQueryBinarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Data_SQL_Async_QueryCompletedEventHandler(object sender, Data_SQL_Async_QueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Data_SQL_Async_QueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Data_SQL_Async_QueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591